apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-native-counter-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-native-counter-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: request_total
      target:
        type: AverageValue
        averageValue: 1000m